name: DockerPublish

on:
  push:
    branches:
      - "master"

jobs:
  DockerPublish:
    if: github.repository_owner  == 'zaanposni'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build frontend
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/zaanposni-portfolio:latest .
      - name: Push images
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u zaanposni --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/zaanposni-portfolio:latest
      - name: Calculate image sizes
        run: |
          SIZE=$(docker image inspect ghcr.io/${{ github.repository_owner }}/zaanposni-portfolio:latest | jq -r '.[0].Size' | numfmt --to=si)
          echo "I found size: $SIZE"
          echo "SIZE=$SIZE" >> $GITHUB_ENV
      - name: Send discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "🚀 Published `zaanposni-portfolio:latest` with `${{ env.SIZE }}`."
